---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: node-feature-discovery
  namespace: kube-system
spec:
  interval: 5m
  chart:
    spec:
      # renovate: registryUrl=https://kubernetes-sigs.github.io/node-feature-discovery/charts
      chart: node-feature-discovery
      version: 0.13.3
      sourceRef:
        kind: HelmRepository
        name: kubernetes-sigs-nfd
        namespace: flux-system
      interval: 5m
  install:
    crds: CreateReplace
  upgrade:
    crds: CreateReplace
  values:
    nodeFeatureRule:
      createCRD: true
    worker:
      config:
        core:
          sources:
            - custom
            - pci
            - usb
        sources:
          usb:
            deviceClassWhitelist:
              - "02"
              - "0e"
              - "ef"
              - "fe"
              - "ff"
            deviceLabelFields:
              - "class"
              - "vendor"
              - "device"
          custom:
            - name: "zwave"
              matchOn:
                - usbId:
                    class: ["02"]
                    vendor: ["0658"]
                    device: ["0200"]
      annotations:
        configmap.reloader.stakater.com/reload: "nfd-worker-conf"
    master:
      replicaCount: 1
      tolerations:
        - key: arm
          operator: Exists
