apiVersion: v1
kind: Secret
metadata:
    name: cloudflare-ddns-secret
    namespace: networking
type: Opaque
stringData:
    CLOUDFLARE_EMAIL: ENC[AES256_GCM,data:Z3UyM1xxKxc8NqvoYz6yNr4rqA==,iv:tSYpfJz6QSjbormCV+dkfVwBjkJtlw1tamR+1hdGPjw=,tag:R9ypDeDGblPfT20mHbLyEw==,type:str]
    CLOUDFLARE_APIKEY: ENC[AES256_GCM,data:yI2+0q8g7sHskopf6IArjB71Tu7+BVaFT07IXLNC9OsjiWfGBQ==,iv:qTRqBjgxo1DMav9UaAezAdwOcR9QD05c7V2u0j474T8=,tag:S+hOglxclGbKfL3eChfXUA==,type:str]
    CLOUDFLARE_RECORD_NAME: ENC[AES256_GCM,data:/EQzDZTvSakbgPzOrhNeJVxYyyvYdg==,iv:x4Hmg+3h6GEkwqs2u52tHriIC/jGakAqMvT4lUJZNtI=,tag:7a2Y534XJzk+30hjdTATfQ==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1h3rcgxnp3xuw2qeetc5ralh4d6rfp8w77yx4kgqyrmaayc7v24uqx6a4j7
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBva2kreTcyRkp6cmJCWWxD
            VEtSTHVCNG9wY3dYd2hFV0dPOWtwU2paYkcwCit5Q2kwSC9XemMvYWlmM29wUHEr
            K2ZDS0FOM2F4Z3J6eXdzYlU0SGc2cncKLS0tIGpNWUMveUhsc3hLUittME1oUzdk
            UW0yT3M3OFFGclZ4VFFYWktjSWhOdVEKMWf5nHGucxUjjlHheVmzQphnvUKvx2dZ
            6veLDQ85n6kfgiGKyWGoEDCm3ab/wNx2ckBxfj4y862C46sTcLDnCA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-01-29T20:19:43Z"
    mac: ENC[AES256_GCM,data:V6M1H5ZZveHM81wHmMDXKszTalpJTvylZRDijP83imbMtbfdDlvbVsFn0DVZYyg2Uk1nXlSZcEnxVzuw8F637vu2SMZjzLm2V4GvTiGhltYcW6ArmBuX9bUpM1PMXwoXhXw3K9lTAEhkXtG45r1uULrlOfRKLIWv0hcJX5YZEn0=,iv:XvB214ygiqoKYP0S28I8hBTNtEFygOWiyW/HHu829G4=,tag:XMFQOio4fRQmlJGIrMvE9g==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
