apiVersion: v1
kind: Secret
metadata:
    name: cloudflare-ddns-secret
    namespace: networking
type: Opaque
stringData:
    CLOUDFLARE_EMAIL: ENC[AES256_GCM,data:h+OX/OpTDrxIGtOtYMLsCgUENQ==,iv:YMC8QYoPHND8KwLQedjq1X+xYKFFFHvC67q/WAgr7Ao=,tag:e4VIQZExJ55F300gvz5CkA==,type:str]
    CLOUDFLARE_APIKEY: ENC[AES256_GCM,data:O+YBL7KAge4aO7Jb6aTC17+xSFJbYOyzAo0ad5QgdmBjrg1jUQ==,iv:dYNM0NgjpFxCll7QhwGVl0X4XdtiAlcX1i8v/h8CG7E=,tag:MXvCmxRQ3HK0fcSbpfQtkQ==,type:str]
    CLOUDFLARE_RECORD_NAME: ENC[AES256_GCM,data:qqPzdLmtoZsacF8Zq3MLreg+dw==,iv:cBaUCRV7f77gwrwMO+sCZ0LDzs9eV2lsXcC/QZnaRNE=,tag:YHjV+YG5drOl8rsaoNOeAw==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1h3rcgxnp3xuw2qeetc5ralh4d6rfp8w77yx4kgqyrmaayc7v24uqx6a4j7
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBsVmM3RWVrWExhWXRNa0ZC
            cS9BZHBhS1FWZkRYdlgrbUV6bU8wMGVWYlE4CkRjVDNPMlhPSzBHV1BXRmxuM0Ey
            MnhCWnZxS0xGY1hkSVFnUjR2MzFuVlEKLS0tIFNBMnVGeFJNV25XY3d1UDNGeGo2
            UTJaeUsvTURUbW40UjBzellQT3hSYlUK0znCAEV+n65JVuxq2rvI1NCB/3HKrH6B
            PdHvPhPwepfdBztgmLIG8PEfnDUGpgNpbJNNcG/GiM1wkIRI9X0WGg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-02-08T20:02:15Z"
    mac: ENC[AES256_GCM,data:f4n4hETNe6WDiWs9BDKguEvxjDdEp0WltSX8KkM7q5EUC+0T4yBFAYVgDkkGNZtpPeCvasH0NoF7R8t04wIarphrsqRQQBnmqYREp2+ZTrN8BV7VSwaOSd0b/BNFIKe0r6Pi9J/KR7TA2AsRwGHO16ubp8d9xuy6NoOXaNZIeO0=,iv:8PxkU8iitOZo7/db9SGcRQo7s1Q6ebFb0WFA4qhWVOI=,tag:viAkkdbkz3Piq7cmC7XOag==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
