apiVersion: v1
kind: Secret
metadata:
    name: cloudflare-ddns-secret
    namespace: networking
type: Opaque
stringData:
    CLOUDFLARE_EMAIL: ENC[AES256_GCM,data:x1WfyGSh8ZjZDPmWqcyG6r6VEA==,iv:EpTI7x8xG6zshLZBNfsRBBs5SbHN4eYIEdRhlgS5QGg=,tag:BLO5LRQsXu/QjuyZ+SGaFQ==,type:str]
    CLOUDFLARE_APIKEY: ENC[AES256_GCM,data:cukpYqYbE9FwaZle1hbDlCe9084TsVGFHktPGcdWwc3zcmCHDg==,iv:rbwnnadH6zOBf7di5a8QGfTQQcgSlcdIInaI/2PI4lQ=,tag:p3YjEf53gvhdx1xEEMexzg==,type:str]
    CLOUDFLARE_RECORD_NAME: ENC[AES256_GCM,data:7NTLfLcDcLuKIbH7OapXauMKgBLb8A==,iv:hNBf7qYK/OEQ0UFFn7F21qXo045TpwDR3GrnjHd8Vkw=,tag:/QWPvX3m7+72zW4aG8tSqg==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1h3rcgxnp3xuw2qeetc5ralh4d6rfp8w77yx4kgqyrmaayc7v24uqx6a4j7
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBRbStMb2VXLzU0bldMMEpP
            WGxQR1hBKzhtZUREYjJOYTZwQXc1dGFjNHljCmRiSFhwaEVKR0R4bStBcmtxVG5i
            TFpJK0VyK0gvN3pYMGRRWC8zWVNvdW8KLS0tIDMva1luMFBsVlNtLzVxRVU0TkpT
            cDZxMWJqa1EwVDdoOFp1U3h6MXN5WHMKw/lu4c7w8JlHBI+S6iwz0hKdpCrx/ZSd
            0oH6gRIa/1kH17JINlHgGhvFCHxltRxZfYg0mSdoK+nopObkZ28Ymg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-02-05T20:25:07Z"
    mac: ENC[AES256_GCM,data:dr0yL+HO7+RtuTNEJ1Ot7eSKfmM6eKPLkyMikUTHy5LPCpgPKVBhHPZbh8tjaQvMW7k2TiT7AtVZx0vglcf+lCo8hzi4UTUfhsPEC8JwJkSxNJRrUgNeQPWS3fu+O1uHWVTV5u+mbtMnn0xMY5N4diF5HMVC0Rm5feF4ZjGa9VQ=,iv:sSH4nlokkI/LpOHV1ph/YGw0HFv4ZzVREwPL8FdZN0s=,tag:wuXyXvquNqaut7RZfSv/Ug==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
