apiVersion: v1
kind: Secret
metadata:
    name: cloudflare-ddns-secret
    namespace: networking
type: Opaque
stringData:
    CLOUDFLARE_EMAIL: ENC[AES256_GCM,data:nIu/zyhm+cPf2KxMH+6X3fGKYw==,iv:GmWg/kSrJNEflNCs337KLOXkkPJRAAnokdbhqddnmeM=,tag:gcB7NzoRxP9uqTADZtaG+Q==,type:str]
    CLOUDFLARE_APIKEY: ENC[AES256_GCM,data:5oNnK/bcM3GpDA43Wp7R1/I+ACN/OkxmHxO3/ZPpw/f4ZYYAdQ==,iv:SFhGeDKFeeSzJADnsrzpg2GIUpjhhW7eCOGqZuHQok0=,tag:qT0bpwXztSakqgeuwPHdbw==,type:str]
    CLOUDFLARE_RECORD_NAME: ENC[AES256_GCM,data:HrC0ou2fSHuSJ1nHzi0SHhcljiH9vQ==,iv:DCtcGr/FLQ4mlcRqYw7XWitf7pzrWCMnEkopg4jlohc=,tag:MdQ7kPjo4T+1ywm2OQb6CA==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1h3rcgxnp3xuw2qeetc5ralh4d6rfp8w77yx4kgqyrmaayc7v24uqx6a4j7
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBuTURwdWdxb2N6dEJnK1Nn
            NTEyQVp6VXZFVFJndmtzN1QzbWJlc1R4Mm5BCmNNQUFFckFhdmlybm5teXJUaXBO
            L0tHWnZQNTl3aENaZGllSXVRaVB1ZmMKLS0tIHBkWVZOUE1Edlh6VUs3QmZwSCs0
            cXR6aHhqZlJHUkxscGhBTVZnbGJJTHMKhJYc4Nka754FJEoxZMtlL40e+4K6d0HK
            GHvPuAnhegLcm6BirRZEHSoHf8UanRgB0g/0BUBoYStWoyfuMnf7rg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-01-25T21:21:47Z"
    mac: ENC[AES256_GCM,data:mWrRZnJv3/Z2FefIK29Ud4u8OUjGJQzsJJWbAxEu60BolqL6oplK4bSHeO8x2/D+JHrB/sd3aInHmNOvFp/aS47Aw+ymIe4RZeHelvXfi/5KOqpnweolQX/MSh+c7r9uTKZKZbHQKtr3f59s3deXJAqDLuhwuUu4lIqhbcdk8wM=,iv:pBbKI2/AIkENmOCqL3rLsicxxdUcQfYdEJrY8UU+ids=,tag:xYAB5hitLlFxChzdplQGog==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
