apiVersion: v1
kind: Secret
metadata:
    name: cloudflare-ddns-secret
    namespace: networking
type: Opaque
stringData:
    CLOUDFLARE_EMAIL: ENC[AES256_GCM,data:Fkc5/gVT+TuYvGxIanxrXF7E3Q==,iv:YGWnR9iSDlLvll7AElddKodtGibTOhnK6riz9YfcmpY=,tag:WnL20vRWX2XhBbb0INZ1Ow==,type:str]
    CLOUDFLARE_APIKEY: ENC[AES256_GCM,data:Dk+byOBPmiAxOFeOkpjVKUFVw5/UxFquBvN74QApjXTmTgmyjA==,iv:8pKm9R/5fJTRMdyANy3WXpTRdt3e+nrAS65YUXjPog8=,tag:sSCAw3bzqomhgwtEZJcAUA==,type:str]
    CLOUDFLARE_RECORD_NAME: ENC[AES256_GCM,data:OL7JfSmThccFIG8y8xklJWt8T098cA==,iv:ktOv9z8JGh01gygUM8xP2DcY2tmqUCqrZvip6KQXwk8=,tag:g00JZKBMl7NZCYgFyUir0Q==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1h3rcgxnp3xuw2qeetc5ralh4d6rfp8w77yx4kgqyrmaayc7v24uqx6a4j7
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBtNWtRZ1VOOGcwT1J2UDJo
            ZHNoNm5NUER6QXdvUzloYUVTMWtpWlAyZGl3CkJpVU0xSE5ZcituU1FQeEpQQ0VP
            NHJxcXh0QTNuZlpKTjdRdlU4dVAvSVEKLS0tIHo4THI2SHBjUGYrc1labENlMVU0
            RWFxaEZxcGVYVWcxOGx0MW0yK0o5cHMKCOlVCvYtcyJi2nYX6yFD3w8kDkmdtg/e
            u3ns5+GT/dZ7vMay/2VilB4eMVH8H6OSJoWt80l0KOHw8i1+Kmjclg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-02-07T21:28:51Z"
    mac: ENC[AES256_GCM,data:C7rbiGTw75TDby/zkG18GVbXEYa8cItXJ1iAo/EPn4JSbNChe7hE5c4O+CW25KXusV36RvN0pXSEf3TWfg2Q2JM4OwKoGW+EYKvIDpuzEkGUrCcod5CMXwFJIK2lDcKcS3LAgkVVmmuHZdFISlvsg7udyFqqNoxI9TIEt8zG0fA=,iv:nZPoP7yux3YYK5GmgQxUKCXyP2/YULrnmJ6CMP+Mvo8=,tag:deTxxhAxVxJIMNyyWWOtag==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
