apiVersion: v1
kind: Secret
metadata:
    name: cloudflare-ddns-secret
    namespace: networking
type: Opaque
stringData:
    CLOUDFLARE_EMAIL: ENC[AES256_GCM,data:46gc4mY3m1V3Qfur+325utwHKA==,iv:w+hq3thmrwPOSuJq/K+yHU70ZbonwhorgAd78t6mcMw=,tag:1xXww69zyGNHsqgpF+t2fQ==,type:str]
    CLOUDFLARE_APIKEY: ENC[AES256_GCM,data:3r3/gSMLoiIA3rUXFo2u+nSCzmlLTF9LmcN9fpQ+S1wFZv1qFQ==,iv:TTzxDWDj+0Lr5vSWUMf/EhDilEtgjgAKdXToBsHehBs=,tag:wS0vvFhv6PyCO4cNLx9p1Q==,type:str]
    CLOUDFLARE_RECORD_NAME: ENC[AES256_GCM,data:0JNU8qWYJgfiqM+BE0rRYPwqyGfiSQ==,iv:17NHLHc0o+HnpulG9zzNCeE/VDTBMSvoz4/VozmM4XE=,tag:c/rzSY6fr7dsooFyE3EPZg==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1h3rcgxnp3xuw2qeetc5ralh4d6rfp8w77yx4kgqyrmaayc7v24uqx6a4j7
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBWeFRTYk4xL2lvRUdvSmhO
            Vis3N0NzaCtzRGc4bnZvZFgxREZJak9GSEFJCklBZk9Nd0dXajAyempvUzkvQjhH
            V3hkaDQvakQxS2Zjb2UxWnNIN3NrVVEKLS0tIHQ4TGtzbFRaN2Q1SjdLMzFTMVNt
            Q09nRlJVL0U0OGZMWVBLMW5RKzdYWUkK9pXgusVVWuDulppkf8EcUPlWNijyYKtB
            0JR6WXTECM0yzt39xuyDbCAsdOQpyqlxRr9nbNqx1qKVrgSQbwwagg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-01-26T16:04:00Z"
    mac: ENC[AES256_GCM,data:Gf3SYJFBMUtMOVidklOYl2YgXnxjtHWZIsC62MO4Ral3jnOv6mGxb18cZGKisZ9cRrCOOAOL5VelZmC3s5E5cOe+/mjpmtIn2Ahhkc0Uc0Wp7MBqjvWSKGJiFPxGmbVZQFRNk7mFcZCgIdmpqJNiFUL0SNXra6aTiUYEOMpSr5A=,iv:xZn0ju8JEzdPec3jmglp4iEZZpPq6UdlyUZKcTbrqCY=,tag:a2wP6tQAHo7YwvMYnEy4XA==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
