---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: node-red
  namespace: home-automation
spec:
  interval: 5m
  chart:
    spec:
      chart: node-red
      version: 0.22.6
      sourceRef:
        kind: HelmRepository
        name: node-red
        namespace: flux-system
      interval: 5m
  values:
    image:
      repository: nodered/node-red
      tag: 3.0.2
    env:
      TZ: "Europe/Amsterdam"
      FLOWS: "flows.json"
      NODE_RED_ENABLE_PROJECTS: "true"
      NODE_RED_ENABLE_SAFE_MODE: "false"
    service:
      type: LoadBalancer
      loadBalancerIP: 172.16.2.122
      annotations:
        metallb.universe.tf/allow-shared-ip: "home-assistant-172.16.2.122"
      ports:
        http:
          port: 1880
    ingress:
      enabled: true
      annotations:
        kubernetes.io/ingress.class: "nginx"
      hosts:
        - host: "nodered.${SECRET_DOMAIN}"
          paths:
            - path: /
              pathType: Prefix
      tls:
        - hosts:
            - "nodered.${SECRET_DOMAIN}"
          certificate:
            name: "node-red-cert"
            issuerRef:
              kind: ClusterIssuer
              name: "letsencrypt-production"
              secretName: node-red-tls

    persistence:
      enabled: true
      storageClass: "longhorn"
      size: "5Gi"
    resources:
      requests:
        memory: 350Mi
        cpu: 25m
      limits:
        memory: 500Mi
