---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: kured
  namespace: kube-system
spec:
  interval: 5m
  chart:
    spec:
      # renovate: registryUrl=https://kubereboot.github.io/charts
      chart: kured
      version: 5.3.2
      sourceRef:
        kind: HelmRepository
        name: kubereboot
        namespace: flux-system
      interval: 10m
  install:
    timeout: 15m
    replace: true
    crds: CreateReplace
    createNamespace: true
    remediation:
      retries: 3
  upgrade:
    remediation:
      remediateLastFailure: true
      retries: 3
      strategy: rollback
    cleanupOnFail: true
    crds: CreateReplace
  test:
    enable: true
  rollback:
    recreate: true
    force: true
    cleanupOnFail: true
  uninstall:
    keepHistory: false
  maxHistory: 3
  values:
    configuration:
      startTime: "0:00"
      endTime: "4:00"
      timeZone: "Europe/Amsterdam"
      rebootCommand: "/usr/bin/systemctl reboot"
    metrics:
      create: true
    service:
      create: true
