kind: ENC[AES256_GCM,data:+ZslM8A4,iv:0mAPWJoubT3Hd2Mrx9hX271qvVWZ9AiwXejqtfTQ0oU=,tag:2blDFlfY9pU+EgVTWQ/uJw==,type:str]
ansible_user: ENC[AES256_GCM,data:9qJJypPL,iv:EqlVfoeR1YyPu8i8LGDsVEOOWbOubSLDXxr+Brk4Vzk=,tag:FHHyHHajsSKaRYY5USEZMQ==,type:str]
ansible_become_pass: ENC[AES256_GCM,data:L9drf/GJ,iv:Nsc3d7uk4r1z3OsT2bmqhAqsY8vjALwUy1ItXzs2qHM=,tag:aMHcSHnd4AtS7hiaXY6VCg==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1h3rcgxnp3xuw2qeetc5ralh4d6rfp8w77yx4kgqyrmaayc7v24uqx6a4j7
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBWdGJPQUU0VEtXdXYwaC9t
            czdidXJnRWRHN2VPNTRMd3NBRnp4eFBwOTNrCnFrcTMzbmMwWWhCOTR0NTlQQTRP
            ZFF5SkU3WmNtSkl2NGEzbHVnK2hnR1EKLS0tIDdpL2J6anJIeHlldENubHNucHFK
            OVMzVDVBOFFBVE1Vbjk0Z1BUdHFDY3cKQXwvZtFQH5YNKjbaQue5cC6xXPC7A8Vk
            ZcTPLN9M+Mlqk3MQysZKr72/ffE3Tqfl9QhuiTP+q4zs5l/zg3+bAg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-02-05T12:31:37Z"
    mac: ENC[AES256_GCM,data:XvgE+wRoFq+AU9QMxCBSMaNYeDenMuBAtYecpmyoYTmF9FLCrdQWPzRs/UrCwMKoKDKZFr2vpp54Ba7a+hk5Dh4sGSkAwzAO7BSZ6/PKqkjcmvp0fanQPZz5rkiPzb+FYlTiqs/oOqB9Sv4btmNASE91XTbIlu0YXwo/fXxSSz0=,iv:qhpJCq/E7qVFX8cxJfQvPBjWPAjS70YVFa5qtwb0IgE=,tag:t1IPIg/2ZOEAF7bIWakrGQ==,type:str]
    pgp: []
    unencrypted_suffix: _unencrypted
    version: 3.7.3
