kind: ENC[AES256_GCM,data:blKoqXIA,iv:YKfozM6SGquKijOpdolyhdGj6JvNX4GxMHWUWPPQQoU=,tag:/A7TlBsrodQ7gK5Jon+tyA==,type:str]
ansible_user: ENC[AES256_GCM,data:SfsZPm0F,iv:6TC4+PL9dem3b0Mi86q4fEdlGhkMszo/cN7WSSrNnq0=,tag:RvbWTUObn1KVydFhaa5U5A==,type:str]
ansible_become_pass: ENC[AES256_GCM,data:mtnv7jg0,iv:uT/X9g5e5NvV1QsqowegUlESTj5HsNRnrsPodO/KNz0=,tag:XjPIzKkM60FVwKM+VvnC2A==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1h3rcgxnp3xuw2qeetc5ralh4d6rfp8w77yx4kgqyrmaayc7v24uqx6a4j7
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBpQmsxZVpKTFk4YklMYjNY
            WDQrVlZWdVErM25rSXVVWDVkNlJpUCtPZm1JCjlYU3BYbjlZcUtER09DL21Ncm9B
            OVVqbkxBTENRTS9PSGZURmNQQS9HQXcKLS0tIFU4L1ZPUnBXRkJIYS9VZi85WGZw
            YVdNVHpBZ21QT25JVkFoQmJ6Qlc3NFkKmD+kOpUAb+LQeHobQsaEjIlNWIV0cMGB
            uM5W9QEeIF8CfJJY17mpqbeXOCMTwaNfx1BNUobqfuZ3qY7BoHjQwg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-01-29T20:19:43Z"
    mac: ENC[AES256_GCM,data:+NlKpqHEJxK/3FyGEltxo9AK3DuREM+/3fMb7iN7TbMG18/Ew7ND2ygaah9QFqaojxwCmloXvftFmX0SsxKNFF9wnOi1D+ykqDR8PCXOjGeHU/9mAHIaRoQovO3FNRFfaEQmd38L2HNbR2z3MeLv1ULzfOo+gl6HC6HTCPF5t0A=,iv:CPcWcTkKkzOdQhcTZZa360xyJVQdZdALtVWe+KEMlR0=,tag:InMH/sQk7SS2offTbVHuuA==,type:str]
    pgp: []
    unencrypted_suffix: _unencrypted
    version: 3.7.3
