kind: ENC[AES256_GCM,data:VmGWB4d7,iv:bj+chHhm2F0FEMlLm/zSdXY4U6M8Kf6hn9uC5MIaLb8=,tag:oPwD+6wqrwjlw78QKTPztg==,type:str]
ansible_user: ENC[AES256_GCM,data:FpvZgIK1,iv:kp1bfaYDbtohIfeYKa9kF/SXpk6UxaIp3Kx/Svhd5uM=,tag:p9x4346EhtleQxvXSwlZfA==,type:str]
ansible_become_pass: ENC[AES256_GCM,data:tdWmRGtK,iv:CMgwvVY8lZaply4mMq9AFgcBeVzMzI5l/GNb1VeNNok=,tag:rHWdq1dEyXQF7Vmh5kIknw==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1h3rcgxnp3xuw2qeetc5ralh4d6rfp8w77yx4kgqyrmaayc7v24uqx6a4j7
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA3c1ROd2FOdi8ydVd0VE1s
            VVo1OHdWdWJaajEvQkRCQkpCMTVaa1lET3lFCkpxS3VUYnFFUitrWC9tNjBwL1JI
            VEN2cDN1L3BEa3o2TFZkOFNlS0x5ZkEKLS0tIEp3ckVIUVZ1TGJiN1dJL0JNeWIw
            T3hFcDhzMGZNMDBsZ05qU3ZDVkVZV1kK7yUqoVDAlhYYFYbSM+8O5gK64GdDMIJS
            4SurbtZPDTee3GEoUKcoF6w8pCwEFLqGMbdiRIoa+Kx7JXfSnw7X1w==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-01-26T16:04:00Z"
    mac: ENC[AES256_GCM,data:R2wHzVWDD+LOQ+sdyGo9RVot33Tuj5389Tqf/fRykQJJ4w3Q1Pz03LNiDqI0Y4Z36GxOQViP1UxEDVZfA80/TFm8tE3ntSVUukiHLJJm4ZvtW1CqiP+GE6ya+6Gu0pAN7jz1889WgtunxP32v66Ms10xVWshkAk7vLQng4pQalk=,iv:ZB+Wek2t1ggBWXrJPAE1uVrn5wRvHxR/iAsEjDN9XdU=,tag:2qPu+splwEjJCr9ThQ7JGg==,type:str]
    pgp: []
    unencrypted_suffix: _unencrypted
    version: 3.7.3
