kind: ENC[AES256_GCM,data:r9rbvn+5,iv:K0nVDDvkjmRHQnfAs0S9z1NaSQOX6NWtai8sElR6Yh0=,tag:t3omJLeAzQ4Gex65gFpWgQ==,type:str]
ansible_user: ENC[AES256_GCM,data:rkVd/9p0,iv:ifcnaFyxsyrR+FxIlcMaVMIJ5Ae0YPe1DZRcKCrab00=,tag:ujA62f1C8ZLStFhd1G2cuw==,type:str]
ansible_become_pass: ENC[AES256_GCM,data:1bbP0nKY,iv:yAMnV76sOJ5pkq9bETr8qt2PGvv5bZCjP/zqm70HL4c=,tag:lXvt6b5GHOlCCVhasLDKyA==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1h3rcgxnp3xuw2qeetc5ralh4d6rfp8w77yx4kgqyrmaayc7v24uqx6a4j7
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBTVG9TVDZoMHhsSitObXpz
            NGFENVUrNHk2MTJZQlQ3c2U2ZzRmWnJqeVhvCnN3SGxJRXFiUHNnK3hCYXlBa2lh
            UnVsT1Y1WVE1bFlVZjBEaTNPV2hmVG8KLS0tIGZkQjR3RWFEU0tNWmszZjNYS3N3
            c3R5b1pLNnI5T3N5c0dUSlgzcHNYMHMKE0Kym3joOybq07G/S9Ad6whWOzl/LraA
            IGiSlxdIhrkeykho22SJqduotIxSRakakNyJEa1M0eoJ9vrYg/qCZw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-02-08T20:02:16Z"
    mac: ENC[AES256_GCM,data:HchQotY+jhjCm9EOHH3G6eaEszvlrB7ux+F0DT9zFRzpQ3jVZfYFS//T2GmGXsA11VYArDO08yho/GKAJBrXdE2zvssOnQRpT75aMdL0sLsxTB0RZJXSu4tYSd5B73S2ClVTp+YdOauB5Js1eavEpcIXnCxGmGvn36B3nLbmbdM=,iv:yxvj0hIHK6OLD3MjJbeAAR+pe9bBF5kNP7UE3KXzrt0=,tag:6WbuysFoiBhbtb30QpyF5A==,type:str]
    pgp: []
    unencrypted_suffix: _unencrypted
    version: 3.7.3
