kind: ENC[AES256_GCM,data:qczePDfr,iv:bdeYtN26+73waq4RYQz/I2b1NDve5qcbk4GD8wsV2K8=,tag:NRAv4LS0G6dZ93x28tSoNg==,type:str]
ansible_user: ENC[AES256_GCM,data:SWWMUAmL,iv:uYYZlaM8LHMWJNo574sbRpm6duBvwESS1NQFGb5/AMM=,tag:YAzXdl4F8zVuNaqg2g3/ZA==,type:str]
ansible_become_pass: ENC[AES256_GCM,data:k5vfqpc4,iv:p+TVhXC1sg31kI0lZonWiy333tDsPcD0Y5FFhncAeX8=,tag:kGS0kiYhbXT2GpkYiwJX0A==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1h3rcgxnp3xuw2qeetc5ralh4d6rfp8w77yx4kgqyrmaayc7v24uqx6a4j7
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBXa1U5S3lYMlNOYzlYd2w5
            TzAxRHZtcWV6VE9EVVVCdDQyVUl0emNtWEF3CkxQWWF5WmttOWt6dWJjVXdZQUVq
            K1FyOFYrcFpmb0tvVXhnMkpXRWRaTjgKLS0tIFVpRnY2MGZod3NXZWN5bklVVVds
            VXB6V0NVWTdpdHAzRnI2NFVVeUN3ZHcKp2xSqHGC952TYIB9HisSJIk3mdaVUE9p
            cUyTrItIO996grjq6a04E6Zhcpv59LAxzEiFHLkZtvR++h/TgFH83g==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-02-05T20:25:07Z"
    mac: ENC[AES256_GCM,data:KS20U6H+DvXIyp/N0hZVGP8bBJWunmh5wBP0d2d2RYhfnhD/nwptGaxLVqDIW5el1IO7PJmcXI0RnTUNRpPb/OPRuVZvfI6Q1kvkdUTgpNqHM9gMtiF8weSNGhQbLTyTxKOQGfS0Qd80DnNpcgcwr13nWvbgxFcA9daqTxEfkXE=,iv:4H0NfFLZHamMD1sLBkhC2OtNPppuAVxNJukQWjk2mCw=,tag:pov8DIneHs49kd8GTl/YkQ==,type:str]
    pgp: []
    unencrypted_suffix: _unencrypted
    version: 3.7.3
