kind: ENC[AES256_GCM,data:HWNRQrxR,iv:47qms5TDI70Swbgp4H4E0pcnSPLIDdJnQlFwokFvjj4=,tag:z9fIDZGrUmIJNlj8Rw5TMw==,type:str]
ansible_user: ENC[AES256_GCM,data:C1SS/zAr,iv:GXeW5nPaE4D9r9n1YDXrjDhuvN68RKYBETz6lKYrIrM=,tag:wfvKjCWni6M3RNi+eRMV9A==,type:str]
ansible_become_pass: ENC[AES256_GCM,data:kDjeokvc,iv:gu0W0uVphJjXJf5wIOSkRZXmhGpYD7d09hAO5q0wnAk=,tag:rrkG0I4y9oF9iTr/QYYh0w==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1h3rcgxnp3xuw2qeetc5ralh4d6rfp8w77yx4kgqyrmaayc7v24uqx6a4j7
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBwK3lIbXE2VDA1SERPdFFT
            UU41MXdISnNwYTM4UGJLaldvc2FkWlhYYVdFCm9FRkZlVVZndWJRQlpLRXN5Lzdo
            aWJzYVRXZ3hoWGpPcGV5NXZTNXRrZFkKLS0tIFlpbUJPRVFRVkJtZEtyZDBVSmJy
            L0o4cmxyakdnNXlFb0xwTEovT0NESk0KQykIR/k+Jyau4WZ0x6r2ZzQlrt5gMcKE
            4XT1K+GeHsyn7Ft5qCu6cambZDlCRa/6Jcqtp3RyV4WwiujqADGksg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-02-08T17:41:42Z"
    mac: ENC[AES256_GCM,data:rCQSSjq02tctyYr8A9oNHngHsAgWRPXPmnqdI9STiT9L7QTZPIOgGvwXM3Oj+wRF6/GyH4vtCE2JDooFe/TlSY3F7jS0g5p6Uw1E3QTEmQL72rgjf/Yf5YrqPi0X62oguL+Qw3qAkCQWx3bDq8mSLEw2hxxVP5kn0TuuU2KgpEU=,iv:acS8g18BbzK6RUnQFUfM3QabjEoZgIK1jeT9vJnoIeo=,tag:s+CGpQEBbMyMF+X5UOUUWw==,type:str]
    pgp: []
    unencrypted_suffix: _unencrypted
    version: 3.7.3
