kind: ENC[AES256_GCM,data:obMOdsT1,iv:D/H69o/hDmE6/hEqaoUef4dDsCecQCT6NX++ZNuS3bo=,tag:zXkyIBEArSy2iZMdlNjPkQ==,type:str]
ansible_user: ENC[AES256_GCM,data:VjeQAgnJ,iv:RQCLb9Qo82CtD7I8wxhvwiFZIKntySKmAu0N531oiYI=,tag:/fDmAb00K6snwTbAbwG8+A==,type:str]
ansible_become_pass: ENC[AES256_GCM,data:5D3LqZhT,iv:Rod6JBHOLflCakqomSSAPQi/+8Ep9RQ3RkO8YxArqss=,tag:CaKRkHw8CEMhvNeQwCfWCA==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1h3rcgxnp3xuw2qeetc5ralh4d6rfp8w77yx4kgqyrmaayc7v24uqx6a4j7
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBxMFZWMU1jSDRoZHFjeVNO
            RVM0elZobjlJV0VjelNiUEpZN0ppMTdQMVVJClB4eDJqMXVWRDdNSjlSM1czTFh2
            SmpFUjVJN2UrL1dZSXZVMHB0YUpTQzgKLS0tIHYyTGJOQWZLODVSb2ZQaXpFWXk5
            OE0zc0ltS2YzaUZaeWlsdnBhVkFpVGMKFlaKhZtUvJJgUyoovfSOqfgK52+8YtRs
            0Lvyll01t5VqTP6o+r7c0VEYWN0sDIrcKrsG8t6W9tpD22ODTsBvvQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-02-08T13:54:15Z"
    mac: ENC[AES256_GCM,data:VBVoBM+uHR5G2ocf4zGOPKuohLlPiK49K2NfkCt8bhu/ApOgDWZsv3eULynW91LMM2Yop4ZGdOOPv1sQLM0RXVsYf4SLdFwtabAb6c00VzIvq0ExdNNqDyVCazYu7pdVTVqmkRVGSSWW2zkLpL65zvBnlPIvb0C/W6mqp3RuACM=,iv:u/HlmmWuaUsgQeK0Gj+KBsM3tKKICJ1qBeeK6MpN4po=,tag:bVHYkeEJrwaPJsy151BavQ==,type:str]
    pgp: []
    unencrypted_suffix: _unencrypted
    version: 3.7.3
