kind: ENC[AES256_GCM,data:dhEhco0U,iv:3mBDcxiqOiMqcEPO0/FPNUo8nVcsjM/e0dIgxsO6qfc=,tag:6qIOWVRqFBWHI06gXi0KVw==,type:str]
ansible_user: ENC[AES256_GCM,data:a5C72ESR,iv:qNhPyOzhwBe+CXhCzZrCqdUSKCiyZv2G9zHBJHHZ9vw=,tag:HFWrN1jaVqn8XCDiAhJK6w==,type:str]
ansible_become_pass: ENC[AES256_GCM,data:acha9wNQ,iv:gWVwjVAnw3PF3pAOHZhnmRAm2MwMsm9CNHcEUvffq+M=,tag:Dld9zzmX74tqvX7XUWCzQQ==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1h3rcgxnp3xuw2qeetc5ralh4d6rfp8w77yx4kgqyrmaayc7v24uqx6a4j7
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSArczZnaXloY3V2cUEyWE5x
            RFdqUFVYbkdqcmpPcHcrNmtLbkZIbGFNQnhRClpSRVI4SWJuUmR4ZldmZHc3dEJD
            WXhxMXExOGMrR1dhNkNhaW1MYTFaR00KLS0tIFRsNm5tTGJaQzkzT3B4Ym85bm00
            enJJRHk2dmViRmZHZUc3NzFYL00wWlEKzdDp6cyJRuFQ2G8c1GJuOWPOk1oE34ey
            dtXEdxCWBXGcJnG+Tem8EMmenIDGyZx1RKvpLyMeYazyAhNTkYcXpQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-01-29T20:56:54Z"
    mac: ENC[AES256_GCM,data:4TzZzFefoGsfo6/nMWQNfWrlAoj8vAZqo3qQyaEGyYUwcngqHVptskClIF28Z6iyDho8JmIUfVDjEIUmMsb7zUEk3jWoNEeN/ltZJfTCYCWSFu6LEdVsLQN/9KkKN6u8+WkF85MY4Hr+IPSHXxXCwx9ccrgVh3iPPy06rNezuFk=,iv:hMN8PKwijCPkguSxVFaK1BLD6XsTcF+PeFaAuVtbhsA=,tag:bccehE/aotKia2ObhNpBLw==,type:str]
    pgp: []
    unencrypted_suffix: _unencrypted
    version: 3.7.3
