kind: ENC[AES256_GCM,data:mgC9u+kI,iv:WGm8hkw0haLdZRNysu+FKYjVPRAlhFHGIgIDL8pi7UU=,tag:FFXgaxLDIg5s6+ASisrPXQ==,type:str]
ansible_user: ENC[AES256_GCM,data:rKgEm0A2,iv:CRYrEhZMZ2Gwb4ESoV2iwQ1g3WfaktRpBjk+QqOSCLI=,tag:aws5gBpc5kMHkCULFJwUsQ==,type:str]
ansible_become_pass: ENC[AES256_GCM,data:qrapmXuO,iv:4lPb1HaLaDlDX95BJIGqgXvhCJBG7Zs1w4uY80QIOik=,tag:anH/zvnUzOg6+g8H9Yc4gg==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1h3rcgxnp3xuw2qeetc5ralh4d6rfp8w77yx4kgqyrmaayc7v24uqx6a4j7
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA1NDV1SWJVdXBsTlNHb2kv
            d1luM2xXZXIxWFRQR21hWkdESUp4emFoOWdBCkNCRDNvcWVwM0E5eFNrTDVkTllG
            V0pIMzUweG9SSFRzaHhKT2ovM0E3WVkKLS0tIGxPSVFoQmpFVVh1NklxamphSTk2
            MkdaTSs5cWhjdk5uU0FnSG1ZNTFUdGsKW9nFr5DeZ+YsIM2vVnk7ZdHw13AoNoli
            5mXs6JdgeUiBKZmvhvLU3cD4v3hNNJbm23FYZRUibRA2Nc+npUIrqA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-01-28T21:23:39Z"
    mac: ENC[AES256_GCM,data:OeTPjSxuv+wBF/3pe8OG5D6OrZAVQzq2L376V5BUjftgNB6OV2pTpWf8d2IQirW6biWzqpMUVo8i8EMs0kkCwiv4L4htbRt6/4cvotIz3ZiQ+wlheHVD0TlfexSLEqLf0Be5TNfuEt2peIOKxLfZ3F5KuAzbXhMXJN82xIUd0N4=,iv:dEBRP3blSM/tf+KbrVE2zGOcfoFZ64AsYWoNtNvzJVo=,tag:ANXcGfSa6k6Jg8ggAtXiKQ==,type:str]
    pgp: []
    unencrypted_suffix: _unencrypted
    version: 3.7.3
