---
apiVersion: source.toolkit.fluxcd.io/v1beta1
kind: HelmRepository
metadata:
  name: t3n
  namespace: flux-system
spec:
  interval: 10m
  url: https://storage.googleapis.com/t3n-helm-charts
  timeout: 3m
