---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: pihole
  namespace: home-automation
spec:
  interval: 15m
  chart:
    spec:
      chart: pihole
      sourceRef:
        kind: HelmRepository
        name: mojo2600
        namespace: flux-system
      interval: 30m
  values:
    image:
      repository: "pihole/pihole"
      tag: "2023.03.0"
      pullPolicy: IfNotPresent

    persistentVolumeClaim:
      enabled: true
      accessModes:
        - ReadWriteOnce
      size: "500Mi"
      storageClass: "longhorn"

    admin:
      existingSecret: "pihole-secret"
      passwordKey: "password"

    serviceWeb:
      loadBalancerIP: 172.16.2.123
      annotations:
        metallb.universe.tf/allow-shared-ip: "pihole-172.16.2.123"
      type: LoadBalancer

    serviceDns:
      loadBalancerIP: 172.16.2.123
      annotations:
        metallb.universe.tf/allow-shared-ip: "pihole-172.16.2.123"
      type: LoadBalancer

    podDnsConfig:
      enabled: true
      policy: "None"
      nameservers:
        - 1.1.1.1
        - 8.8.4.4
        - 8.8.8.8

    dnsmasq:
      customDnsEntries:
        - address=/pihole.bluejungle.net/172.16.2.123
        - address=/longhorn.bluejungle.net/172.16.2.122
