---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: esphome
  namespace: home
spec:
  interval: 30m
  chart:
    spec:
      chart: app-template
      version: 1.4.0
      interval: 30m
      sourceRef:
        kind: HelmRepository
        name: bjw-s
        namespace: flux-system

  values:
    image:
      repository: esphome/esphome
      tag: 2023.4.2

    env:
      TZ: "Europe/Amsterdam"
      ESPHOME_DASHBOARD_USE_PING: "true"
      ESPHOME_DASHBOARD_RELATIVE_URL: "/"
      ESPHOME_QUICKWIZARD: true
      ESPHOME_IS_HA_ADDON: 0
      DISABLE_HA_AUTHENTICATION: true
      # USERNAME:
      # PASSWORD:
    service:
      main:
        type: LoadBalancer
        loadBalancerIP: 172.16.2.122
        annotations:
          metallb.universe.tf/allow-shared-ip: "home-assistant-172.16.2.122"
        ports:
          http:
            port: 6052
    hostNetwork: true
    dnsConfig:
      nameservers:
      # Set to your router IP or local DNS server
        - 172.16.2.252

    dnsPolicy: None

    ingress:
      main:
        enabled: true
        annotations:
          kubernetes.io/ingress.class: "nginx"
        hosts:
          - host: "esphome.${SECRET_DOMAIN}"
            paths:
              - path: /
                pathType: Prefix
        tls:
          - hosts:
              - "esphome.${SECRET_DOMAIN}"

    persistence:
      esphome-cache:
        enabled: true
        type: emptyDir
        mountPath: /config/.esphome
      config:
        enabled: true
        existingClaim: "esphome-config"

    resources:
      requests:
        cpu: 300m
        memory: 512M
      limits:
        memory: 2048M
