apiVersion: v1
kind: Secret
metadata:
    name: cert-manager-secret
    namespace: cert-manager
stringData:
    api-key: ENC[AES256_GCM,data:9EGJztChDp1YDfDhgi2T3wpFvtWSrulLnamiXY0otJ2Y0uMJ0A==,iv:U4hZa/led1ncE+55l9tHAlxb1PM3BPOhq0TgZxBg51c=,tag:gs4pG0Xi5R2PJRMlPhJY1w==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1h3rcgxnp3xuw2qeetc5ralh4d6rfp8w77yx4kgqyrmaayc7v24uqx6a4j7
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBGMGVYMjg3NDR4Q0duTU9j
            bDRTUDhza1dDb28vVE9TZ3R1QUxOK240elYwCi9zV3BteXdQbW0xSVg3ZGZtUXRP
            TmV3elVlZXNJVWQrdjVha0FETHRsNDAKLS0tIHl5Z1Y5UzFHNStFM3M2R1pNTGRW
            NDZxYUhOS3ZBS010U1MvVW5OaXdxRTgK37kys1QSF3Iw7kedYugKakHLiu2foCS4
            u1cAVsHOR0/UyqWX0xE+qIzpffP0AUJ0pDuQzQk2Sj920t0llu0f+Q==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-02-08T20:02:15Z"
    mac: ENC[AES256_GCM,data:WK4hCRKj/PE3hJ7P5mjm92+Tni8RFdBj+gTJIr81c0+JaJGKg2ALb/ER3VvdUENeTUH7XQDYdc48io2pDWfcjPFbU6pke3byqAxJYM0iEbZFL7BAD31OJueRgW92+FmMx2AXBimR6CJt81klF5OiM+RML7QdQnNI8q0KZps9xaY=,iv:lgDDhzrlw+dtNwMyaCiwtu7V7sYuQbzMn3fH2uIV8dM=,tag:oAxUT+zK9ym+fbQQJFcamQ==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
