apiVersion: v1
kind: Secret
metadata:
    name: cert-manager-secret
    namespace: cert-manager
stringData:
    api-key: ENC[AES256_GCM,data:1e/wX7JtaQC/v4fwJBp9dILM5Ud+Z0SigKNFvRwDVGRJRhGkaQ==,iv:CREs/J+19IZI6TC2vAlMdHDPtMx+3/prWaJXFFN0rmY=,tag:UnEnnqwO3LhI//1GpZ55+w==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1h3rcgxnp3xuw2qeetc5ralh4d6rfp8w77yx4kgqyrmaayc7v24uqx6a4j7
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBkQXM1M0pkZkRzWEpkRWdQ
            dEZEeVpvWjZPR0UySEY5NTY3aEFPVDlxakdrCkltYVdTV2RkM0RuRkNuZi9ILzEy
            NXdTV3ZxN2oreG53OG5UQkIxdDU0WHMKLS0tIFpCZkFwd1Z2OExQbUM3ZUtpdmlD
            cVNMNVFaS3lpck9XcHJQVTZtNXdZRkEK7055z6YCa8r//iGE36MWIVU5YMzgeldr
            CqShGkuSATS06DP4w6NEwF3wnNu1RPCbYVgW3UVzjKxwIIwissb/aA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-02-05T20:25:07Z"
    mac: ENC[AES256_GCM,data:arAlS/H6DPfSxdew+MfHymbkyfQbsuMj4dJ5aNeiaYnJeXa9GPza4Kr0m4/Vprypmlwbs/22EkHgFXz18/zHSm5YWyFupTStT3mLQKc2b+2y5028ANhWDANeBa7SQUsu9Fs0cDCQor5uA8CjJstmjCVLHzYivIVwNX09UCptk3I=,iv:xqqMFxAam1kTeta/sCQJbBsOi+ZO3BGLWyLjDBGvQh8=,tag:t7TpdpnhxEluAD7FZ4DGSw==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
