apiVersion: v1
kind: Secret
metadata:
    name: cert-manager-secret
    namespace: cert-manager
stringData:
    api-key: ENC[AES256_GCM,data:aJicW0CviQWX6cMwFDZPHBaH3jHFLCtMpiOHo4UlKPtiRNSM8g==,iv:NfM5J8v9OPJM+3igY4lRmUR1CYiidtl8IC20Xcp9ZLU=,tag:q4sarBEU/3xHyqiDJ6T50A==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1h3rcgxnp3xuw2qeetc5ralh4d6rfp8w77yx4kgqyrmaayc7v24uqx6a4j7
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBaeTZIcm9oVHRCOHFGaDFt
            N3d3WmJiMmp1R3JXMy9wR0JIQjlqUnlkenpBCk1TOTRXMGlNOW8wZ2RlcitZZEk0
            cWtNY0p5K2lDakZYOFF5UzMrZmNBNmcKLS0tIHVCbDZkQm9TbEdxcE9DaDFmMWs4
            S2pCemVxc0tROXZSdUplWXAydVdYZjgK4g87ARuPpOiGIiWcrZQUztl4Y/yIO1J5
            /UbNBd8RshbeRpcaCDMX94y3e3th0fgm40bbjobC+vGH5R9XW+juJA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-01-29T20:19:43Z"
    mac: ENC[AES256_GCM,data:LIlDl0vqODzjWhdqGYJdDpuwgCxKEiDHjeqWY6ooWFABJtcNwuaxP6MZLwTlAj7t6Uq6lHgMA/6M6ed20lQ3RdITYCUYhmnR/x5eKW4gTsHq+uJepEwuFCyvXJ6T6EY2oygy3NFcPvPi40ysuBFq3ynqAUNAoD5AChYBbZIDGgM=,iv:id0lxKtIfYqT8a90TdEV92t0aaUoIbGUoK99+gr/0lI=,tag:wisKFBav0RqWIwwfMqo4Vg==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
