apiVersion: v1
kind: Secret
metadata:
    name: external-dns-secret
    namespace: networking
stringData:
    email: ENC[AES256_GCM,data:YOo2qdNWnWtJcXNnQQ171ZhYRw==,iv:33ZjDf1dS+rm3gQbw23LXymoNq8RtTWPBlbpOsJRea8=,tag:O1BfI1d3jNXd/O1DzxxBHA==,type:str]
    api-key: ENC[AES256_GCM,data:P9YwN83UsMn87yY1Rti/NnXeWyaFD/O0MOIpAwB4CcJQNPF2yA==,iv:OSv6v58Bafma/bxbZOG+1pQB9ifmYsyXIi/3bSVM6AI=,tag:qdunbN0s3mOyl/DB+KnJbw==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1h3rcgxnp3xuw2qeetc5ralh4d6rfp8w77yx4kgqyrmaayc7v24uqx6a4j7
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB2aGE3VGF5aVFHL0JJREls
            S0x1UjRnUnFuMzBHNVY5YkFJQ3MxTXZVMURvCnNZUDR2WjVVaWg3T2V2Q2hPTWhs
            cFd1Y0NaN1FOVlFWZ21WRmNHSkYyTHcKLS0tIFVITXZVN0hkUldTZS9Gelp4Vkx1
            RXY4d1RGcGNlSFd1WGRsT0JweE40SmcKCohlpla2OeD+WGGXEb/hdoWDoR5EGwHN
            WBOH4tGaCMCpGHARafkizfnanQovE8hX2vsYU1xakH81h5HurHXT1A==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-02-05T20:25:07Z"
    mac: ENC[AES256_GCM,data:rxOStAY+d+9qFIw/DhMZ3tHTrl6TFL6kWNem87jBbUT5chuZ3DaH+bMzZ3zqj4XF9UE2mvbLGpc6j85dmRyz61Gd1YuYzHFTdh6Z72mZ/eB0sFlSCrYUmMq8IQl4Cysl92BRngGlGIEFlU2wo1GkH2KAq7K6lN3oTEwr1YQRJd4=,iv:93F5OVIJf+cttQzLQaEBFNum6n2dV+5bD3AbJtfbeZI=,tag:ijEIlI1eVJ4LanLxIe5vqQ==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
