apiVersion: v1
kind: Secret
metadata:
    name: external-dns-secret
    namespace: networking
stringData:
    email: ENC[AES256_GCM,data:o3ZLwaPWy8b9TcLVLtu3d4asTg==,iv:YLqePN0p5c/rg4NITtdQgVdk5murC9TYP40QtAj7cCk=,tag:PPbUAf9DuYm7Ou+tRnaqsA==,type:str]
    api-key: ENC[AES256_GCM,data:hlzYVg/JYbynPpB6KfMWkiqHabP0xTIP0bEr6mKWzbRCb5017g==,iv:WXx7NZElr54lNj+lnKw6OkJGv4yZ89p15wDyrrrEgsg=,tag:KvGxd3GgHhNl723TkRvI5g==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1h3rcgxnp3xuw2qeetc5ralh4d6rfp8w77yx4kgqyrmaayc7v24uqx6a4j7
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBQdFcxWUw1ZHI4WWFUNkgr
            bWF4ei9zWUhyU3ZORWVjbGZSZGdlcXFQWHo0CnN2bUtkcGtQbVlXUTVsTGZTWWFP
            c2JuVXpxdVpFNHhGZzlzdml3OXltOTQKLS0tIDZ4cmpyems5UFNjWno2alBDMENr
            SlJrb1hQdFoxNXphUDY2U1NmckJBcEkKEk9PeJUOCogc40LPcOhjZli4HzqaS2ng
            cYoEzWZiqw0zOLYTUsE5MiuYOp0yT2Wa91g2IS2Nz4o9LSQ62ZlDYw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-03-20T12:05:25Z"
    mac: ENC[AES256_GCM,data:YjTCRhLFQKVJKGH2fhpF+OXl1SXD1G8I3+s0jiBmoz9Vf5f4uv+vF3FlQftw+SFcVWhvBbsmDt16Wbw0Yc8nEF8QnJcJT9x2y4UpGl51d8K4AFy1Sz4lpHEfQ7k63CQgA1+tELX9BcbQ/h+7BgA+hNsCdgAR46q9kkVXZwUqduc=,iv:Y5xF9iXZBdYHeFakdpa6acM7ZOri8PonFTwRekK6lxQ=,tag:zhqPmLGP/VS3Q5zNRSu/Qg==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
