apiVersion: v1
kind: Secret
metadata:
    name: external-dns-secret
    namespace: networking
stringData:
    email: ENC[AES256_GCM,data:DEqqQKIXx8fJtGHOD4ahMF8p1g==,iv:gPcA+rpRwAHYiAZMl8nNwfoIJrrGex+2FxklbGX24fY=,tag:wIqGGUAv1/qOvUpcFDDTvQ==,type:str]
    api-key: ENC[AES256_GCM,data:lO7DPi8brCL5PnLWvfOs0GYVh57aWe1G1YJ0/EQlrZS0YKp1+A==,iv:pXa8+p1CA1xF2DZnj5UWmfGvoeN3842nEwlo6Ik6lGY=,tag:O4Qc30aJpLUaLnF4Ec/LQQ==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1h3rcgxnp3xuw2qeetc5ralh4d6rfp8w77yx4kgqyrmaayc7v24uqx6a4j7
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBHcVcyeVFBY0VWa2cvbzU2
            V3pReHRCUHhtTkVaNEE1ck43ZjcycWFIVkZvCmJiNzIvbHFrbGFQNHJWVEc1ZnZU
            NHVkQXhyRTNRbERpU3owN3ZVeUJvUmsKLS0tIERiRWRPT1pKUEpMYXNUWFlGeXM0
            SFdZSDVBaWE4aFBqWGpwcngxK3ZpKzQKlwIERAR83Np/V75o9ojkOJuKvfDIKURn
            gukpVXSsW2lra7tSjJFb1V36CnoOmiDfhMOcmzVIZRTgzbiOonkGjQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-02-08T13:54:15Z"
    mac: ENC[AES256_GCM,data:hMWZmn2ajC1FsPbR3bl8zEQRs9AC9lkQbMukkY4um8aM2v3C2xeVVCJGzW2pIhlqdqqLz8A9a0/KkeFG494v+BBVWPZ3i5ejGgjvMBRC5/pUfQrspQMR/p/R15hBGKXqDwiRUWH3SnQ0gBlbBFGSCU6tux3Dv2t4iRXd77KhKt0=,iv:6/doDOo/luQxXWFw/hRrzLeBFDgj9GMVouGJoxQ0jWA=,tag:7foOo8VtTm3VWI6j1lKh8w==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
