apiVersion: v1
kind: Secret
metadata:
    name: external-dns-secret
    namespace: networking
stringData:
    email: ENC[AES256_GCM,data:/G2SdMCsizuyGIRfwEM3juZlsw==,iv:g5iElabkDcY/Ik/9BuAWiNN8fh6Cr5LNUe800vRMx3o=,tag:HZ2mYL7iKRA9qhSGBmgkgA==,type:str]
    api-key: ENC[AES256_GCM,data:61KBjYpB2qS/Vzjc32ls9ADeyVEDPxVb3m46c6cut9aIlfNsfg==,iv:FfAiGEojjTIOTQjpvEw3i9tjb0Ii11Lxsly69lRtmpA=,tag:ADuRpBeHZUHTeJGp1WMNkQ==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1h3rcgxnp3xuw2qeetc5ralh4d6rfp8w77yx4kgqyrmaayc7v24uqx6a4j7
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB6WnljV09PYWY3SGtjR21N
            ZzRCb0s0UG5zazVTUDZjZ00wZkdLOWVxcTJ3CnhFM1VoVWl0Tno1RGU4U3hKSk5K
            VElXKy9FcS9CN3piQjVRYnVWWWYyU2MKLS0tIHc5QzBudngvdVZQcDQ1aFpkdEhC
            cGhUd3k1bDNXYmdiYjdCamlyRDFmVncKsYpbnoQ2NVTgUoRodsAboKGA+CD8Ie7j
            FyRjg0vVsAo0iSdrQWj3l1PZtLKr3XTFJxC2Q2NxhNxMMDEEId574Q==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-02-08T17:41:42Z"
    mac: ENC[AES256_GCM,data:XtNqiWIi+wOqKfx++xJNzzwqwde21DMVwRssAYL2H/Rcmcyo1tIhLyK/3J/PzX1cnfZs1oM+Unm0rQygdl4mqWrBlxCY1Em0NxfUCQm6rU3xA+TFjEP9GuLRY7qzc09tRTLvN2hqrV6nWoywkz6T1JMR4EgdnkEV/AbmsUq+tl0=,iv:67vGjJijXDpi6OPGqygtSZaJW4+iyl2IKssKUiPFg/g=,tag:x/kRJ0dtaXPC9SF7n9dCvw==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
