apiVersion: v1
kind: Secret
metadata:
    name: external-dns-secret
    namespace: networking
stringData:
    email: ENC[AES256_GCM,data:batnSdXkFNkA1JnQfLZBgFXuRw==,iv:PxfryEY027qdpLzr/bWFCCbMQNWmtke+YQ2zQASDdg4=,tag:p7C1++l0kadbGHqXP6AckQ==,type:str]
    api-key: ENC[AES256_GCM,data:1hXGZV/1t0Dsd5OPCnSI9PAP5F31/ZIcuJwdnd9H2+8lMnMyCg==,iv:hL9k9x0Xku3tX9TbLA/iRtpDjRanH+V9vyeYJAkeITc=,tag:He0XlYJA4j+is87on/m3wg==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1h3rcgxnp3xuw2qeetc5ralh4d6rfp8w77yx4kgqyrmaayc7v24uqx6a4j7
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBmMURlb0RUanNDTkhHVFI1
            ZTNldE5wT1NqQ0wxWXBkMmRBQ0xnVE1hMVU4CjdURkxYaFFvbzdmaHoybmFzOGVk
            ZDI3TWhhdjZsWjNtK2s1NnZNQy9jSG8KLS0tIFFNL2ZJMlUxUEFiUXhMVDF5WnV2
            MlQ1TUdQZTJzTGo0N20zd2RoNUV4UDgKyykZFpKhEN9ivT4b+2ltFMtrnDCtDAP3
            /4+KLG0m5Tz7NljLeKMGQ0Ku9MFccD1Or0dAeOtBkl06umXjGKmC0g==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-02-08T17:51:34Z"
    mac: ENC[AES256_GCM,data:qNN13sLgW9hDEzr/ateUhVh7RyBUJm2IXM/kc2ThOI+F0sxmgh0J7UG3VnVHA1rT5zwpC7G+WJS9aWhV3UBgy/ZEgg9xflG9cLQr+XpnsCkQO3rPMSfbwV/4DyV88qG1GAwktope9qH6lpqFxI2OEvrWhQo+MYRgoiHqIvfzmYI=,iv:yw5CW4YuQ/XCqWixDoTJL7LApCMiXzcXbcw70BGJt7A=,tag:8aNZ1gE94xBF/8ar05ayGA==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
