---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: zwavejs2mqtt
  namespace: home-automation
spec:
  interval: 5m
  chart:
    spec:
      # renovate: registryUrl=https://k8s-at-home.com/charts/
      chart: zwavejs2mqtt
      version: 5.4.2
      sourceRef:
        kind: HelmRepository
        name: k8s-at-home
        namespace: flux-system
      interval: 5m
  values:
    image:
      repository: ghcr.io/zwave-js/zwave-js-ui
      tag: 8.8.3
    env:
      TZ: "Europe/Amsterdam"
    securityContext:
      privileged: true
    resources:
      requests:
        memory: 200Mi
        cpu: 50m
      limits:
        memory: 500Mi
    service:
      main:
        annotations:
          metallb.universe.tf/allow-shared-ip: "home-assistant-172.16.2.122"
        type: LoadBalancer
        loadBalancerIP: 172.16.2.122
        ports:
          http:
            port: 8091
      websock:
        enabled: true
        type: LoadBalancer
        loadBalancerIP: 172.16.2.122
        externalTrafficPolicy: Local
        annotations:
          metallb.universe.tf/loadBalancerIPs: "172.16.2.122"
          metallb.universe.tf/allow-shared-ip: "home-assistant-172.16.2.122"
        ports:
          websocket:
            enabled: true
            port: 3000
            protocol: TCP
            targetPort: 3000
    ingress:
      main:
        enabled: true
        annotations:
          kubernetes.io/ingress.class: "nginx"
        hosts:
          - host: "z.${SECRET_DOMAIN}"
            paths:
              - path: /
                pathType: Prefix
        tls:
          - hosts:
              - "z.${SECRET_DOMAIN}"
    persistence:
      config:
        enabled: true
        emptyDir:
          enabled: false
        mountPath: /usr/src/app/store
        storageClass: longhorn
        accessMode: ReadWriteOnce
        size: "1Gi"
        skipuninstall: true
      usb:
        enabled: true
        type: hostPath
        hostPath: /dev/serial/by-id/usb-0658_0200-if00
        hostPathType: CharDevice
    affinity:
      nodeAffinity:
        requiredDuringSchedulingIgnoredDuringExecution:
          nodeSelectorTerms:
            - matchExpressions:
                - {key: "feature.node.kubernetes.io/custom-zwave", operator: In, values: ["true"]}
