---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: cluster-apps-mosquitto
  namespace: flux-system
  labels:
    substitution.flux.home.arpa/enabled: "true"
spec:
  path: ./kubernetes/apps/home-automation/mosquitto/app
  prune: true
  sourceRef:
    kind: GitRepository
    name: home-kubernetes
  healthChecks:
    - apiVersion: helm.toolkit.fluxcd.io/v2beta1
      kind: HelmRelease
      name: mosquitto
      namespace: home-automation
  interval: 60m
  retryInterval: 1m
  timeout: 15m
  dependsOn:
    - name: cluster-apps-longhorn
    - name: cluster-apps-ingress-nginx
