apiVersion: v1
kind: Secret
metadata:
    name: weave-gitops-secret
    namespace: flux-system
type: Opaque
stringData:
    adminPassword: ENC[AES256_GCM,data:kWRFi7hbLVFqkr+9mjD5FPDGkxpm98roRX5Fvg392FM2sp7PuNvAi2hfRnCHRP7vqwv+f5Z1CpUuzter,iv:Pg8JHNgZnCMuLpvo/jIWw9jQLfW6GJr9XBYjf/B9yiQ=,tag:djSiPCq0WnGHb209Zcj/MQ==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1h3rcgxnp3xuw2qeetc5ralh4d6rfp8w77yx4kgqyrmaayc7v24uqx6a4j7
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBSZmxjYzBjNm9LN081cFNS
            eWp6NnplaEc4TTFUQU5FQSt1QVYrUlg1NndVCk5TaHkwcW1OTHRzTXFKSzB0d21C
            N1ZtMVRWQmM5T2gwd3lwZVB0VWFaYWcKLS0tIFlHenNEVFNmYUpsbkdTYjBMRVRE
            dGttOXJNY252blE4RDFQekwzUkY2SEUKNeGTvTJJSoR2MAI5jhI5aq1E7bOAhwt0
            n9868EWIregikDUJpwxEY9qHONMXH2rzzeO3wQVmd/TONuKOy6WasA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-01-25T21:21:49Z"
    mac: ENC[AES256_GCM,data:lmYechKdmGTCb649Faw8KeOwCQYkkw+rYoSUNpCxuH4TFSWuoE+hKlYTj/G4eDri/VMtmhbnoW0sDlWSh8+lRgxJNdoROQ43hFN3wHIXtPYyUEYbEqmGJbK3/yIStbbAUftVxcHUfZLrEM+mJCqNuEQ9yQSkCp+qx1/jphJynwU=,iv:eJEJZRJ8aZRAlroVC3A8F69vcnXPe6Ixe1y0SdkmEtQ=,tag:WbfVnJZX0Tm5qOYbFAABZA==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
