apiVersion: v1
kind: Secret
metadata:
    name: lidarr-secret
    namespace: default
stringData:
    LIDARR__API_KEY: ENC[AES256_GCM,data:q09PvbIXDU6YdAV642W9JGEDnpsI7v34qX3Xkd0bnMRKNKoYEBuVyhwacqhwL7Xn78QDlqRNZvsriTJgeV/AFQ==,iv:K1CmiOsoAojMuFm325IES8PLOp5jMtFocsZ5w2WK388=,tag:aZizy9W6br1H7yM8JoDtwQ==,type:str]
    arlToken: ENC[AES256_GCM,data:RxW+squRkPaIzfs1F5go,iv:DBz+Sa61Lp6u8InNjffLngkv4z4hSsTrw9s1CdecAmQ=,tag:7OslVMdk3xkVGp/z+2aZeg==,type:str]
    plexToken: ENC[AES256_GCM,data:2fcXAACbCfSybBdDznaS,iv:VTlLYNr8UpHljzpsPeeOz308+8gc1MRa98oZGuo3gv0=,tag:DPobp8on2VyT5JfhReGX1Q==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1h3rcgxnp3xuw2qeetc5ralh4d6rfp8w77yx4kgqyrmaayc7v24uqx6a4j7
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBjS0trN1dieStlaWVDa2xq
            Z2F2Q2JHNmR0ODduNUZGZUJmUGhpWTR1Snh3CjZKN0x6bXVMTGd6TDJoeXByOGhv
            ZzVDczFWM1VWU2UzY2ZzZjR4aW93bTAKLS0tIERpWWoxS0puZzdhZ0Z6bGZXR2pr
            ZzVsbmwrcDQzSXBlQTRIdUU0cDF2MHcK5j476qhj8lOmukLiw7aJV5OEy/+EebLr
            vIBL+V1D/JcDnDp1pdch1SbLX4ts/RMD4ArckF76b9i2CAEzVbok/A==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-02-15T10:42:51Z"
    mac: ENC[AES256_GCM,data:k12v0GM0ZBbMHkt+ncO30ynxAH+yh7Dg4obwdc9YdrKFMKzgBYxmZyy8SqUXVNJdyw1K8iphenQQWTs4cluxpu90fOOEV1gUpKl2sETbIjDlFF0OGLNgyQlt6slooteIF3cyMAsFZZyw8FXbj/ABHwRm46FqwVYNpNAaUHvIqeg=,iv:oIaDTgEuxCYHyVigXhoe9A+05lssiD4/casoojT5Ce0=,tag:+7jlnDGbaFCCrjgJ/JXUGA==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
