apiVersion: v1
kind: Secret
metadata:
    name: cluster-secrets
    namespace: flux-system
stringData:
    SECRET_DOMAIN: ENC[AES256_GCM,data:sY5DErrZID1XyupicPV+yLA=,iv:fwADbkiyPEAnCO1HdFid95C16MRVl/zH35HnOdH2Y/g=,tag:83jsMPzmNKNB7Otx5aPOtg==,type:str]
    SECRET_CLOUDFLARE_EMAIL: ENC[AES256_GCM,data:LvLXVO1WKYvo6AjDMiy3R0so2A==,iv:wju9/hw5TzdiuhP8wWJbMA8na3O+gvQFLHFX/uIjo50=,tag:yHgFPlmWyUNyw4lewS/aGw==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1h3rcgxnp3xuw2qeetc5ralh4d6rfp8w77yx4kgqyrmaayc7v24uqx6a4j7
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAvZWQ4VHMyOUhFTmRmcmUw
            aTQ5S3BrNkpSU0VHTm44LzRrK255a3JaOXlNCjBJaHRIOUd5bWtOZHNHV2ZDRE5y
            dFErR0ozYmtsRG10KzZQTS9pWU5KQU0KLS0tIEliZzkya2haUENtRzZJNFBsdnYv
            MnpTVFo3RWJpTVNrUHpNc0Z4TG5FL00K9ciPGftWBs5gbvPz/ReXydYbiKcnMFAN
            EbJh4e3kUFgZr0ytDoVxvJyAOHSLBdien/cYjgRNQ3MIWwlDZEnJ/A==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-01-28T21:23:39Z"
    mac: ENC[AES256_GCM,data:wba/+Y05O08y1CsCCjkTkEqhczi4zxkuOuVoOgDYmH+VUvaMDZNJQkP+AXG+9zTM3JEhhX04+GDGse6HXSMZlmOVczgIFb6ZT8y2efKHwyE4tDNfjtYzBjGOAIafTnsVcUx+5G17YoxC2rSNOEkNtHcSiB9vDS0BwzFqzySNA/U=,iv:LMT+BM8wlTttO2R+qpzJPWUHENNUjNfyxwcPIpn0fU0=,tag:aRCZGOWm8Tb1hqSD0yVuQg==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
