apiVersion: v1
kind: Secret
metadata:
    name: cluster-secrets
    namespace: flux-system
stringData:
    SECRET_DOMAIN: ENC[AES256_GCM,data:k/aEIVtKNEJonhn1KPCKaxM=,iv:/qK92LxjGBEXg96XbcLaApL4qx0f3/2rIJVA/z6fRuc=,tag:Q7ucbXDg4f0lhUiavCEjpQ==,type:str]
    SECRET_CLOUDFLARE_EMAIL: ENC[AES256_GCM,data:WFP+hVZab6GMZJi4dX45XS7mUA==,iv:yLePzmGr8gBmIdjF0v70pUonEOwdsIfOCzSngYtKJ50=,tag:YEVrAxEvC03kdGbACHCH0Q==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1h3rcgxnp3xuw2qeetc5ralh4d6rfp8w77yx4kgqyrmaayc7v24uqx6a4j7
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSByZCtGeFVMRmkxOUNLUzFE
            NGZvcGgwU05xTVhHOVhjK1ducHFtQjNxU25rCkdHa3ZOM1lqQmt2dFh3a1BGUEph
            bHVYNzJsSWVlc2RTeHNoVmd2TUo2UlUKLS0tIDU5cnpHTnlzeVlRNXhvQnNRbFBm
            eUZvbGxHNE5QVnNyY25PTUpqMTdpYWMKeI4lphLiCby6WftKMF6xSBn6D7BMiZaW
            CHRHwAryLUi2ZPC/KKsptKB7z+Jf19dfLpDdc2uwpmrDpEnOdxy7ow==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-01-29T20:19:43Z"
    mac: ENC[AES256_GCM,data:qSpnOLKa9lcLkUhGG8LgrHfIXHSQXGdi5abcXohRhZ8CTyzmAAn3haDrWAwX2a2idTW/Dcxf7kGUt/y11rnqNoa0zAxgpqeOp/zVf/63H6JmufWkbNyZQyWqkP0ESLbq2gZY+x097+zFgIV9lbTp0aPrAbizs9Ok/MR1AA2PXq4=,iv:n2/qzCxvY8SokjSHJyDperUAafm93kp51EOpy7NfW08=,tag:8daEU5SfuPfj2IohQ2210g==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
