apiVersion: v1
kind: Secret
metadata:
    name: cluster-secrets
    namespace: flux-system
stringData:
    SECRET_DOMAIN: ENC[AES256_GCM,data:GSpzy7o4RBYYd4rzux7C7ds=,iv:zpLiQqybooyofq70VMm/8j/hzoe6wl6TGe2qggRpxc8=,tag:i9uU6E/wRVXN9vLRL3V4UQ==,type:str]
    SECRET_CLOUDFLARE_EMAIL: ENC[AES256_GCM,data:OvfRLHLHKDungRI6P+ZQ8lLjsQ==,iv:EFGw8cI/CTZhhGC0W8cYHIbe6UptqQKtxTMxb2By4v0=,tag:GPcv2N9X5af12Z27TRaYSA==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1h3rcgxnp3xuw2qeetc5ralh4d6rfp8w77yx4kgqyrmaayc7v24uqx6a4j7
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAzMjRJYXREVGlDaUs4QkNo
            UFh1cExrU01YQzIvdko4dUMvbWNaUDRrejNvCmtRSFNUMWlUeFdIQzZTaVFOWW5D
            MUJpTkdVVHd2bzBqVlR5VG9GYnFiY0kKLS0tIEIxaFFQQmdrYU5MSXUzODVzQk1q
            Qm9GVFo4dEJ6UTEwZXhlTXFXYWhNSEUKW5kB2Bv3BiyKFxmKo8F5qmQy4RjGvAZt
            Um/G0ojthsXv6vcJ2htorgGv385bxSV4JDC+b3F+fIWSNYQHQ0NKCQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-01-26T16:04:00Z"
    mac: ENC[AES256_GCM,data:2DXM0mISAbfDzAhdzS7e/fi3bvNHY46mehfTgIT1dvY9aXvVgu8n4o2s3OI0tlYEgHX4Fw6HrPglvG+FZ//LvcRqjGymthXtorTQoZCNy5G8Uop3oETZgMa/tKrUn/FITuPahU+6dnN4jVingDlw8QVsM8YrQ2Lyu6D29ppF6rY=,iv:Ppc63v/cfQhks2Rp7k/FANBo71+zHtNl1ghb/Tib7ow=,tag:THP9zH0jRHpEOsff/zpCEQ==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
