---
apiVersion: v1
kind: ConfigMap
metadata:
  name: cluster-settings
  namespace: flux-system
data:
  TIMEZONE: "Europe/Amsterdam"
  KUBE_VIP_ADDR: "172.16.2.110"
  METALLB_LB_RANGE: "172.16.2.120-172.16.2.130"
  METALLB_K8S_GATEWAY_ADDR: "172.16.2.120"
  METALLB_INGRESS_ADDR: "172.16.2.121"
