apiVersion: v1
kind: Secret
metadata:
    name: cluster-secrets
    namespace: flux-system
stringData:
    SECRET_DOMAIN: ENC[AES256_GCM,data:jzMSp2J62UZ8OArpymvgcXY=,iv:BJAIPrjJE2+/TaGWMNRfVStJ1dAx5GPAAIb0gBaDQns=,tag:W1+vw1wt95D2j0h95dyj3w==,type:str]
    SECRET_CLOUDFLARE_EMAIL: ENC[AES256_GCM,data:Q1HF7NAR0vAibQ/0stQyP7m1LA==,iv:EBsuVVdoDtrUd2+K0LwzHYxHoOj5Kxb/va1TlrEjo0g=,tag:ScVaM0reBSdkQRdHu34F8Q==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1h3rcgxnp3xuw2qeetc5ralh4d6rfp8w77yx4kgqyrmaayc7v24uqx6a4j7
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB4cURiVXdCcWdvQnhObW9p
            TGM0NVNQQWVLOWx3a2UzNm85TUd2M2F2ZmhzCmpEWDVWV21YUE9JMzNaRU9HcGti
            Nkl1UG1UcDBHR0lsMG5JdkJ5Qy9uVkkKLS0tIFVodUVCUGNHSG83L0ZNMEpTZEFY
            cnpING1xQmpNM2V6SVpaU0lrYXhUNzAKbxjj+I78hand9OaFYcESE2R/mBuXCs1f
            YjA4zU/TqYnoLhoowSjjsUPxChIFw4/LB9GHJq4t8YV1/rnEl9JkQw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-02-05T12:31:37Z"
    mac: ENC[AES256_GCM,data:Zl50zHoZxtSAN5Be+YPQ8Jo6MnfBdKkYt5MJHESylWiqwmC3l5VuwZcFmcuXAo84s9SdAyzARihDE+7ODqU4kLxhpgOPgDAtMChG7cXLA6ZmmSItwtCz8Yun1rAaU41UoZSLqNdUDsjl1cDwXXtBrtK+UNbPcgpZWWRlpNJ4qQE=,iv:8+scACNw4VQUi8+ijEHwRed/KwBC3XmE9yBORLPJkhE=,tag:+Nj86/2QpVn04GI99UGSsQ==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
