apiVersion: v1
kind: Secret
metadata:
    name: cluster-secrets
    namespace: flux-system
stringData:
    SECRET_DOMAIN: ENC[AES256_GCM,data:ADjY2Lr8Hxg2b45sDpfbjoQ=,iv:bWnAjAT470zjA+X9zeO2ig1oqhTzAG146HX8c9cH+bE=,tag:D+jtHMdzOplIupjE/hGVog==,type:str]
    SECRET_CLOUDFLARE_EMAIL: ENC[AES256_GCM,data:YCFcKNjD466m6lx7eZucGPAb4A==,iv:6IhmIar0cFSZPHKAILQlrjNvtHj+Il359onutxVJuuk=,tag:Kj+wXkxS37k/MlU5U9MiOA==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1h3rcgxnp3xuw2qeetc5ralh4d6rfp8w77yx4kgqyrmaayc7v24uqx6a4j7
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBSMXlqTUJiNW9TT2l3OXZR
            bzhFVlpyNnFQalJveDV4YU1xR0xJeVFjV3g0ClVUd1l4L2hCZEwwU2ZWQXNCMnF1
            bDdxZGJBSFYvZGlYS2tidE5RYlZGUGsKLS0tIGhkdmlHQXp2QVlVMDNlZXdwTmVm
            eGFWSTRvSGczak1ka3pIY0d5Y0pGc2cKH2dE2DVOwF89COI8Vx0pvLRKNRPL8cNE
            gfFqWyFs3nwwcKfbc8rj2pGME2/BXYVNwYHQ68z3v90Dl9gDvB1GeQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-01-29T20:56:54Z"
    mac: ENC[AES256_GCM,data:4TFD5TScQmijpoKT0az7Ga5pKhGnTsnUgrXYoRoz2J8/6Q0cpxYltoH/A18CFG/TN6FhtLTebRP1A0QcyHC1WeiusUDwue6/q0qbkZBJIh5Ris5+l+VpwGNEiv6BLQ/XEJDRWpF75BSfwc/En5H0vU7S6s9fB3TuZ+NF3x3IRpM=,iv:9hXBLpK2LeyNJhCql4pAf89wvUURpr4wFQka3DvNQT0=,tag:z0ikwPSKc+QT3GYNKXJDFQ==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
