---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: longhorn
  namespace: storage
spec:
  interval: 5m
  chart:
    spec:
      chart: longhorn
      version: 1.4.0
      sourceRef:
        kind: HelmRepository
        name: longhorn
        namespace: flux-system
  install:
    createNamespace: true
    remediation:
      retries: 3
  upgrade:
    remediation:
      retries: 3
  values:
    persistence:
      defaultClass: true
      defaultClassReplicaCount: 3
      defaultFsType: ext4
      reclaimPolicy: Delete
    replicaCount: 2
    ingress:
      enabled: true
      ingressClassName: nginx
      annotations:
        cert-manager.io/cluster-issuer: "letsencrypt-production"
      host: "longhorn.${SECRET_DOMAIN}"
      tls:
        - secretName: longhorn-tls
          hosts:
            - "longhorn.${SECRET_DOMAIN}"
    defaultSettings:
      backupstorePollInterval: 300
      backupTarget: nfs://${NAS_ADDR}:/volume1/clusterbackup
      defaultDataLocality: best-effort
      defaultReplicaCount: 3
      createDefaultDiskLabeledNodes: true
      nodeDownPodDeletionPolicy: delete-both-statefulset-and-deployment-pod
      concurrentAutomaticEngineUpgradePerNodeLimit: 1
      storageMinimalAvailablePercentage: 10
      StorageOverProvisioningPercentage: 110
      defaultDataPath: /media/storage
    resources:
      requests:
        cpu: 100m
        memory: 128Mi
      limits:
        memory: 256Mi
