---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: home-assistant
  namespace: home-system
spec:
  interval: 5m
  chart:
    spec:
      chart: home-assistant
      version: 13.4.2
      sourceRef:
        kind: HelmRepository
        name: k8s-at-home-charts
        namespace: flux-system
      interval: 10m
  test:
    enable: false # Enable helm test
  install:
    remediation: # perform remediation when helm install fails
      retries: 3
  upgrade:
    remediation: # perform remediation when helm upgrade fails
      retries: 3
      remediateLastFailure: true # remediate the last failure, when no retries remain
    cleanupOnFail: true
  rollback:
    timeout: 10m
    recreate: true
    cleanupOnFail: true
  values:
    image:
      repository: homeassistant/home-assistant
      tag: 2023.1.7
    env:
      TZ: 'Europe/Amsterdam'
    hostNetwork: true
    dnsPolicy: ClusterFirstWithHostNet
    service:
      main:
        type: LoadBalancer
        loadBalancerIP: 172.16.2.122
        annotations:
          metallb.universe.tf/allow-shared-ip: "home-assistant-172.16.2.122"
    ingress:
      main:
        enabled: true
        annotations:
          kubernetes.io/ingress.class: "nginx"
        hosts:
          - host: "hass.${SECRET_DOMAIN}"
            paths:
              - path: /
                pathType: Prefix
        tls:
          - hosts:
              - "hass.${SECRET_DOMAIN}"
    probes:
      liveness:
        enabled: false
      readiness:
        enabled: false
      startup:
        enabled: false
    persistence:
      config:
        enabled: true
        existingClaim: home-assistant-config
    addons:
      codeserver:
        enabled: true
        image:
          repository: codercom/code-server
          tag: 4.7.1
        workingDir: '/config'
        args:
          - --user-data-dir
          - '/config/.vscode'
          - --extensions-dir
          - '/config/.vscode'
        ingress:
          enabled: true
          annotations:
            kubernetes.io/ingress.class: "nginx"
          hosts:
            - host: "hass-vscode.${SECRET_DOMAIN}"
              paths:
                - path: /
                  pathType: Prefix
          tls:
            - hosts:
                - "hass-vscode.${SECRET_DOMAIN}"
        volumeMounts:
          - name: config
            mountPath: /config
    postgresql:
      enabled: true
      image:
        repository: postgres
        tag: '14.1'
      auth:
        enablePostgresUser: false
        username: home-assistant
        database: home-assistant
      postgresqlDataDir: "/data/pgdata"
      shmVolume:
        enabled: false
      volumePermissions:
        enabled: false
      primary:
        persistence:
          enabled: true
          storageClass: longhorn
          size: 10Gi
          mountPath: "/data/"
      resources:
        limits:
          memory: 4000Mi
        requests:
          memory: 2000Mi
  valuesFrom:
    - kind: Secret
      name: home-assistant-secret
      optional: false
