---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: home-automation
generatorOptions:
  disableNameSuffixHash: true
resources:
  - helmrelease.yaml
secretGenerator:
  - name: home-assistant-secret
    files:
      - values.yaml=values.sops.yaml
